# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  PROJECT_NAME: DDNG

jobs:
  build-skse:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: ilammy/msvc-dev-cmd@v1.4.1

    - name: Cache vcpkg packages
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/build/debug-msvc/vcpkg_installed
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('${{github.workspace}}/vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-installed-${{ hashFiles('${{github.workspace}}/vcpkg.json') }}
          ${{ runner.os }}-vcpkg-installed
        
    - name: Run CMake
      uses: lukka/run-cmake@v10
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        configurePreset: build-debug-msvc
        configurePresetAdditionalArgs: "['-DCMAKE_TOOLCHAIN_FILE:STRING=C:/vcpkg/scripts/buildsystems/vcpkg.cmake']"
        buildPreset: debug-msvc

    - name: Move binaries
      run: |
        cd ${{github.workspace}}/build/debug-msvc
        mkdir temp
        cd temp
        move ../DeviousDevices.dll
        move ../DeviousDevices.pdb
    
    - name: Upload DLL artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: ${{ env.PROJECT_NAME }}-dll
        # A file, directory or wildcard pattern that describes what to upload
        path: build/debug-msvc/temp
        # The desired behavior if no files are found using the provided path.
        retention-days: 90

  build-papyrus:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Copy PAPYRUS sources
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: 'IHateMyKite'
        repository: 'PapyrusSourcesDD'

    - name: Run build scripts
      run: |
        cd PapyrusSourcesDD
        PapyrusCompiler.exe "../scripts/source" -o="${{github.workspace}}/compiled_pex" -all -i="../scripts/source;SRC;SRC_LAL;SRC_ZAZ;SRC_OTHER;SRC_PO3;SRC_DD;SRC_SKYUI;SRC_PAPUTIL;SRC_SXL;SRC_MFG;SRC_RM;SRC_FNIS;SRC_SLA;SRC_XPMSE;SRC_SLIF" -optimize -f="Flags.flg"
    
    - name: Delete PAPYRUS folder
      uses: JesseTG/rm@v1.0.0
      with:
        path: PapyrusSourcesDD

    - name: Upload PEX artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: $${{ env.PROJECT_NAME }}-pex
        path: ${{ github.workspace}}/compiled_pex
        retention-days: 90

  compose-release:
    runs-on: ubuntu-latest
    needs: [build-skse, build-papyrus]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Download DLL
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.PROJECT_NAME}}_DLL
          path: artifacts/${{ env.PROJECT_NAME }}_DLL

      - name: Copy DLL to dist
        run: cp -r artifacts/${{ env.PROJECT_NAME }}_DLL ${{ github.workspace }}/dist/SKSE/Plugins

      - name: Download PEX
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.PROJECT_NAME}}_PEX
          path: artifacts/${{ env.PROJECT_NAME }}_PEX

      - name: Copy compiled Papyrus to dist
        run: cp -r artifacts/${{ env.PROJECT_NAME }}_PEX ${{ github.workspace }}/dist/scripts

      - name: Upload release artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: $${{ env.PROJECT_NAME}}
          path: ${{ github.workspace }}/dist
          retention-days: 90
          
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [build-skse, build-papyrus, compose-release]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.PROJECT_NAME }}
          path: artifacts/${{ env.PROJECT_NAME }}
      - name: Zip artifacts
        run: |
          ls -la artifacts/*
          cd artifacts/${{ env.PROJECT_NAME }}
          zip -r9 "../${{ env.PROJECT_NAME }}-${{ github.ref_name }}.zip" *
      - name: Release
        uses: nikitalita/action-gh-release@v1.0
        with:
          files: |
            artifacts/${{ env.PROJECT_NAME }}-${{ github.ref_name }}.zip
